import type { Metadata } from "next";
import { Space_Grotesk, Noto_Sans_Lao } from 'next/font/google';
import "./globals.css";
import Header from "@/components/Header";

const grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-grotesk",
});
const lao = Noto_Sans_Lao({
  subsets: ["latin"],
  variable: "--font-lao",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lao.variable} ${grotesk.variable} h-full font-grotesk antialiased`}
    >
      <body className="min-h-full flex flex-col bg-my-deepest-black text-my-white">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
